### Site Configuration
### https://gohugo.io/getting-started/configuration/

module:
  hugoVersion:
    extended: true
    min: "0.123.0"

baseURL: https://carljin.com/
defaultContentLanguage: en
languageCode: zh-cn
title: Carl's Blog

# Theme
theme: hugo-PaperMod

# Content Management
contentDir: content
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
enableInlineShortcodes: true
enableRobotsTXT: true
hasCJKLanguage: true
paginate: 15
summaryLength: 140

# URL Management
permalinks:
  posts: /:title/

# Multilingual
languages:
  en:
    languageName: "English"
    weight: 1
    params:
      profileMode:
        enabled: true
        title: A ChatGPT engineer ykwim :)
        imageUrl: "img/typing-laptop.gif"
        imageWidth: 150
        imageHeight: 150
    menu:
      main:
        - name: 🔍 搜索
          url: search
          weight: 1
        - name: 🏠 主页
          url: /
          weight: 2
        - name: 📚 文章
          url: posts
          weight: 3

# Output Formats
outputs:
  home:
    - HTML
    - RSS
    - JSON

# Site Parameters
params:
  # Site Metadata
  description: ""
  author: CarlJin
  images: ["site-feature-image.jpg"]

  # Theme Settings
  defaultTheme: dark
  disableThemeToggle: false

  # Display Settings
  mainSections: ["posts"]
  showShareButtons: true
  showReadingTime: true
  showWordCount: true
  showLastMod: true
  displayFullLangName: true

  # Post Settings
  showBreadcrumbs: true
  showPostNavLinks: true
  showCodeCopyButtons: true

  # Table of Contents
  toc:
    enabled: true
    includeLevel: [1,2,3]

  # Comments
  comments: true

  # Header/Logo
  label:
    text: "Carl's Blog"
    icon: "img/cat-meme.gif"
    iconHeight: 35

  # Assets
  assets:
    disableHLJS: false  # We use Chroma
    favicon: "img/cat-meme.gif"
    favicon16x16: "img/cat-meme.gif"
    favicon32x32: "img/cat-meme.gif"
    apple_touch_icon: "img/cat-meme.gif"
    safari_pinned_tab: "img/cat-meme.gif"

  # Social Links
  socialIcons:
    - name: github
      url: "https://github.com/carl-jin"
    - name: RSS
      url: "index.xml"

  # Search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# Privacy Settings
privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    disable: false
    respectDoNotTrack: true
  instagram:
    disable: false
    simple: true
  twitter:
    disable: false
    enableDNT: true
    simple: true
  youtube:
    disable: false
    privacyEnhanced: true

# Markup Processing
markup:
  _merge: deep
  highlight:
    noClasses: false
    lineNos: true
    style: monokai
    codeFences: true
    guessSyntax: true
    tabWidth: 4
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: true
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false

# Image Processing
imaging:
  anchor: Smart
  bgColor: '#ffffff'
  hint: photo
  quality: 85
  resampleFilter: Lanczos

# Minification
minify:
  disableJSON: false
  disableXML: true
  minifyOutput: true
  tdewolff:
    html:
      keepQuotes: true

# Caches
caches:
  getjson:
    dir: :resourceDir/_gen
    maxAge: 24h
  getresource:
    dir: :resourceDir/_gen
    maxAge: 24h
  images:
    dir: :resourceDir/_gen
    maxAge: 24h
  modules:
    dir: :resourceDir/_gen
    maxAge: 24h

# Development Server
server:
  headers:
    - for: /**
      values:
        Referrer-Policy: strict-origin-when-cross-origin
        X-Content-Type-Options: nosniff
        X-Frame-Options: DENY
        X-XSS-Protection: 1; mode=block

# Taxonomies
taxonomies:
  category: categories
  tag: tags
  series: series

# Security Headers
security:
  enableInlineShortcodes: true
  exec:
    allow: ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
    osEnv: ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']
  funcs:
    getenv: ['^HUGO_']
  http:
    methods: ['(?i)GET|POST']
    urls: ['.*']
